In [2]:
esg_words = ['clean', 'environmental', 'epa', 'sustainability', 'climate', 'warming', 'biofuel', 'biofuels', 'green', 'renewable', 'solar', 'stewardship', 'wind', 'atmosphere', 'emission', 'emissions', 'emit', 'ghg', 'ghgs', 'greenhouse', 'agriculture', 'deforestation', 'pesticide', 'pesticides', 'wetlands', 'zoning', 'biodiversity', 'species', 'wilderness', 'wildlife', 'freshwater', 'groundwater', 'water', 'cleaner', 'cleanup', 'coal', 'contamination', 'fossil', 'resource', 'air', 'carbon', 'nitrogen', 'pollution', 'superfund', 'biphenyls', 'hazardous', 'householding', 'pollutants', 'printing', 'recycle', 'recycling', 'toxic', 'waste', 'wastes', 'weee', 'climate change', 'conservation', 'environmentally', 'footprint', 'global warming', 'pollutant', 'recycled', 'sustainable', 'sustainably',
'citizen', 'citizens', 'csr', 'disabilities', 'disability', 'disabled', 'human', 'nations', 'social', 'un', 'veteran', 'veterans', 'vulnerable', 'dignity', 'discriminate', 'discriminated', 'discriminating', 'discrimination', 'equality', 'freedom', 'humanity', 'nondiscrimination', 'sexual', 'communities', 'community', 'expression', 'marriage', 'privacy', 'peace', 'bargaining', 'eeo', 'fairness', 'fla', 'harassment', 'injury', 'labor', 'overtime', 'ruggie', 'sick', 'wage', 'wages', 'workplace', 'bisexual', 'diversity', 'ethnic', 'ethnically', 'ethnicities', 'ethnicity', 'female', 'females', 'gay', 'gays', 'gender', 'genders', 'homosexual', 'immigration', 'lesbian', 'lesbians', 'lgbt', 'minorities', 'minority', 'ms', 'race', 'racial', 'religion', 'religious', 'sex', 'transgender', 'woman',
'women', 'occupational', 'safe', 'safely', 'safety', 'ilo', 'labour', 'eicc', 'children', 'epidemic', 'health', 'healthy', 'ill', 'illness', 'pandemic', 'childbirth', 'drug', 'medicaid', 'medicare', 'medicine', 'medicines', 'hiv', 'alcohol', 'drinking', 'bugs', 'conformance', 'defects', 'fda', 'inspection', 'inspections', 'minerals', 'standardization', 'warranty', 'endowment', 'endowments', 'people', 'philanthropic', 'philanthropy', 'socially', 'societal', 'society', 'welfare', 'charitable', 'charities', 'charity', 'donate', 'donated', 'donates', 'donating', 'donation', 'donations', 'donors', 'foundation', 'foundations', 'gift', 'gifts', 'nonprofit', 'poverty', 'courses', 'educate', 'educated', 'educates', 'educating', 'education', 'educational', 'learning', 'mentoring', 'scholarships', 'teach', 'teacher', 'teachers', 'teaching', 'training', 'employ', 'employment', 'headcount', 'hire', 'hired', 'hires', 'hiring', 'staffing', 'unemployment',
'align', 'aligned', 'aligning', 'alignment', 'aligns', 'bylaw', 'bylaws', 'charter', 'charters', 'culture', 'death', 'duly', 'independent', 'parents', 'cobc', 'ethic', 'ethical', 'ethically', 'ethics', 'honesty', 'bribery', 'corrupt', 'corruption', 'crimes', 'embezzlement', 'grassroots', 'influence', 'influences', 'influencing', 'lobbied', 'lobbies', 'lobby', 'lobbying', 'lobbyist', 'lobbyists', 'whistleblower', 'compliance', 'conduct', 'conformity', 'governance', 'misconduct', 'parachute', 'parachutes', 'perquisites', 'plane', 'planes', 'poison', 'retirement', 'approval', 'approvals', 'approve', 'approved', 'approves', 'approving', 'assess', 'assessed', 'assesses', 'assessing', 'assessment', 'assessments', 'audit', 'audited', 'auditing', 'auditor', 'auditors', 'audits', 'control', 'controls', 'coso', 'detect', 'detected', 'detecting', 'detection', 'evaluate', 'evaluated', 'evaluates', 'evaluating', 'evaluation', 'evaluations', 'examination',
'examinations', 'examine', 'examined', 'examines', 'examining', 'irs', 'oversee', 'overseeing', 'oversees', 'oversight', 'review', 'reviewed', 'reviewing', 'reviews', 'rotation', 'test', 'tested', 'testing', 'tests', 'treadway', 'backgrounds', 'independence', 'leadership', 'nomination', 'nominations', 'nominee', 'nominees', 'perspectives', 'qualifications', 'refreshment', 'skill', 'skills', 'succession', 'tenure', 'vacancies', 'vacancy', 'appreciation', 'award', 'awarded', 'awarding', 'awards', 'bonus', 'bonuses', 'cd', 'compensate', 'compensated', 'compensates', 'compensating', 'compensation', 'eip', 'iso', 'isos', 'payout', 'payouts', 'pension', 'prsu', 'prsus', 'recoupment', 'remuneration', 'reward', 'rewarding', 'rewards', 'rsu', 'rsus', 'salaries', 'salary', 'severance', 'vest', 'vested', 'vesting', 'vests', 'ballot', 'ballots', 'cast', 'consent', 'elect', 'elected', 'electing', 'election', 'elections', 'elects', 'nominate', 'nominated',
'plurality', 'proponent', 'proponents', 'proposal', 'proposals', 'proxies', 'quorum', 'vote', 'voted', 'votes', 'voting', 'attract', 'attracting', 'attracts', 'incentive', 'incentives', 'interview', 'interviews', 'motivate', 'motivated', 'motivates', 'motivating', 'motivation', 'recruit', 'recruiting', 'recruitment', 'retain', 'retainer', 'retainers', 'retaining', 'retention', 'talent', 'talented', 'talents', 'brother', 'clicking', 'conflict', 'conflicts', 'family', 'grandchildren', 'grandparent', 'grandparents', 'inform', 'insider', 'insiders', 'inspector', 'inspectors', 'interlocks', 'nephews', 'nieces', 'posting', 'relatives', 'siblings', 'sister', 'son', 'spousal', 'spouse', 'spouses', 'stepchildren', 'stepparents', 'transparency', 'transparent', 'visit', 'visiting', 'visits', 'webpage', 'website', 'announce', 'announced', 'announcement', 'announcements', 'announces', 'announcing', 'communicate', 'communicated', 'communicates', 'communicating',
'erm', 'fairly', 'integrity', 'liaison', 'presentation', 'presentations', 'asc', 'disclose', 'disclosed', 'discloses', 'disclosing', 'disclosure', 'disclosures', 'fasb', 'gaap', 'objectivity', 'press', 'sarbanes', 'engagement', 'engagements', 'feedback', 'hotline', 'investor', 'invite', 'invited', 'mail', 'mailed', 'mailing', 'mailings', 'notice', 'relations', 'stakeholder', 'stakeholders', 'compact', 'ungc']

In [3]:
import nltk
# nltk.download()

In [2]:
path = '/Users/coconut/Google Drive/我的雲端硬碟/esg財報資料'

In [4]:
import dask.dataframe as dd

df = dd.read_csv(f"{path}/AR_data_r_v3.csv", encoding='utf-8-sig').head(10)
df

,CIK,Company,Type,Filing Date,filename,cleaned_data,ticker,BIDLO_-4d,ASKHI_-4d,PRC_-4d,...,market_date_t3,market_date_t4,ret_mkt_t0,ret_mkt_t1,ret_mkt_t2,ret_mkt_t3,ret_mkt_t4,cum_firm_ret,cum_mkt_ret,Δr_i
0,1001250,ESTEE LAUDER COMPANIES INC,10-Q,2003-01-30,1001250_10Q_2002_0001001250-03-000028.json,cik company estee lauder company inc filing_ty...,EL,26.10,26.45,26.20,...,2003-02-04,2003-02-05,-0.022849,0.013130,0.005399,-0.014088,-0.005435,1.140802,0.975971,0.164832
1,1002047,NETWORK APPLIANCE INC,10-Q,2003-02-26,1002047_10Q_2003_0000891618-03-001035.json,cik company network appliance inc filing_type ...,NTAP,10.76,11.40,11.30,...,2003-03-03,2003-03-04,-0.013141,0.011758,0.004622,-0.007537,-0.015357,0.961502,0.980228,-0.018726
2,1002590,STAR GAS PARTNERS LP,10-Q,2003-01-21,1002590_10Q_2002_0000950130-03-000285.json,cik company star gas partner lp filing_type q ...,SGU,19.60,19.99,19.80,...,2003-01-24,2003-01-27,-0.015702,-0.010432,0.010224,-0.029233,-0.016160,1.000000,0.939786,0.060214
3,1002638,OPEN TEXT CORP,10-Q,2003-02-14,1002638_10Q_2002_0000927016-03-000732.json,cik company open text corp filing_type q filin...,OTEX,26.95,27.76,27.71,...,2003-02-20,2003-02-21,0.021435,0.019500,-0.007096,-0.009502,0.013224,1.036643,1.037682,-0.001038
4,1003078,MSC INDUSTRIAL DIRECT CO INC,10-Q,2003-01-13,1003078_10Q_2002_0000950136-03-000061.json,cik company msc industrial direct co inc filin...,MSM,17.70,18.25,18.00,...,2003-01-16,2003-01-17,-0.001412,0.005830,-0.014426,-0.003942,-0.014017,1.015873,0.972196,0.043677
5,100493,TYSON FOODS INC,10-Q,2003-02-03,100493_10Q_2002_0000100493-03-000006.json,cik company tyson food inc filing_type q filin...,TSN,10.01,10.15,10.08,...,2003-02-06,2003-02-07,0.005399,-0.014088,-0.005435,-0.006449,-0.010094,0.930000,0.969604,-0.039604
6,1005210,SUBURBAN PROPANE PARTNERS LP,10-Q,2003-02-10,1005210_10Q_2002_0001005210-03-000012.json,cik company suburban propane partner lp filing...,SPH,28.25,28.79,28.52,...,2003-02-13,2003-02-14,0.007569,-0.008098,-0.012687,-0.001600,0.021435,0.995434,1.006267,-0.010834
7,1005229,COLUMBUS MCKINNON CORP,10-Q,2003-02-12,1005229_10Q_2002_0001005229-03-000004.json,cik company columbus mckinnon corp filing_type...,CMCO,2.50,2.64,2.54,...,2003-02-18,2003-02-19,-0.012687,-0.001600,0.021435,0.019500,-0.007096,0.923462,1.019211,-0.095750
8,1005731,IDT CORP,10-Q,2003-03-14,1005731_10Q_2003_0000950130-03-002072.json,cik company idt corp filing_type q filing_date...,IDT,14.10,14.65,14.28,...,2003-03-19,2003-03-20,0.001647,0.035427,0.004242,0.008737,0.001888,1.025623,1.052614,-0.026991
9,100726,UNIFI INC,10-Q,2003-02-10,100726_10Q_2002_0000950144-03-001426.json,cik company unifi inc filing_type q filing_dat...,UFI,4.96,5.20,5.00,...,2003-02-13,2003-02-14,0.007569,-0.008098,-0.012687,-0.001600,0.021435,0.960239,1.006267,-0.046029

### 在底下這格把 前後三天的開高低收都加進去

In [ ]:
########## 1. 載入必要套件 ##########
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import PorterStemmer
import dask.dataframe as dd

tqdm.pandas()

########## 2. 讀取資料並篩選 ##########
df = dd.read_csv(f"{path}/AR_data_r_v3.csv", encoding='utf-8-sig').head(10)

df = df[
    df["predicted_category"].isin([1, 2, 3, 4, 5]) &
    (~df["trade_type"].isin(["no_trade"]))
].copy()

########## 3. 定義詞幹化 tokenizer ##########


def tokenize_and_stem(text: str) -> list[str]:
    stemmer = PorterStemmer()
    tokens = nltk.word_tokenize(str(text).lower())
    return [stemmer.stem(tok) for tok in tokens if tok.isalpha()]

########## 4. 建立詞頻矩陣（raw TF） ##########

texts      = df['filtered_text'].fillna('').progress_apply(str)
vectorizer = CountVectorizer(
    tokenizer=tokenize_and_stem,
    vocabulary=esg_words,
    lowercase=True
)
tf_matrix  = vectorizer.fit_transform(texts)  # shape = (n_docs, n_words)

# 4.1 計算 document frequencies
N    = tf_matrix.shape[0]
df_j = (tf_matrix > 0).sum(axis=0).A1

# 4.2  IDF
idf = np.log((N + 1) / (df_j + 1)) + 1

# 4.3  TF-IDF 
tfidf_matrix = tf_matrix.multiply(idf)

# 5. DataFrame
feature_names = vectorizer.get_feature_names_out()
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=[f"{w}_TFIDF" for w in feature_names]
)

########## 6. 合併文章ID、日期、報酬率 ##########
meta_df = df[['CIK','Filing Date','BL','BH','AL','AH','range']].rename(
    columns={
        'CIK': '文章ID',
        'Filling Date': '日期',
        'BL':'BL',
        'BH':'BH',
        'AL':'AL',
        'AH':'AH',
        'range': '報酬率'
    }
).reset_index(drop=True)

output_df = pd.concat([meta_df, tfidf_df], axis=1)

########## 7. 輸出成 CSV ##########
output_df.to_csv(
    'data/esg_tfidf_with_return.csv',
    index=False,
    encoding='utf-8-sig'
)

print("已輸出 → esg_tfidf_with_return.csv")

In [ ]:
import numpy as np
import pandas as pd
from pandas.api.types import is_integer_dtype

dfv = pd.read_csv(f"esg_tfidf_with_return.csv", encoding='utf-8-sig')

tf_cols = [c for c in dfv.columns if c.endswith('_TFIDF')]
print(f"TF 欄位數量: {len(tf_cols)}")

# 缺失值
print("任何缺失值？", dfv[tf_cols].isna().any().any())
na_per_col = dfv[tf_cols].isna().sum()
print("有缺失的欄位(前10):\n", na_per_col[na_per_col>0].sort_values(ascending=False).head(10))

# 無限值
arr = dfv[tf_cols].to_numpy()
print("任何正/負無限？", np.isinf(arr).any())

# 型別（CSV 讀回來有時會變成 float，這裡檢查一下）
all_int = all(is_integer_dtype(dfv[c]) for c in tf_cols)
print("所有 TF 欄都是整數型別？", all_int)

for c in tf_cols:
    if not is_integer_dtype(dfv[c]):
        dfv[c] = dfv[c].fillna(0).round().astype(int)
dfv.to_csv(
    'data/esg_tfidf_with_return_cleaned.csv',
    index=False,
    encoding='utf-8-sig'
)

TF 欄位數量: 490
任何缺失值？ False
有缺失的欄位(前10):
 Series([], dtype: int64)
任何正/負無限？ False
所有 TF 欄都是整數型別？ True

In [7]:
dfv.head(10)

,文章ID,Filing Date,BL,BH,AL,AH,報酬率,clean_TFIDF,environmental_TFIDF,epa_TFIDF,...,mail_TFIDF,mailed_TFIDF,mailing_TFIDF,mailings_TFIDF,notice_TFIDF,relations_TFIDF,stakeholder_TFIDF,stakeholders_TFIDF,compact_TFIDF,ungc_TFIDF
0,1001250,2003-01-30,26.10,26.73,29.570,30.25,0.159004,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1002047,2003-02-26,10.13,11.40,10.100,10.89,-0.114035,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1002638,2003-02-14,26.95,28.35,27.110,28.46,0.056030,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1003078,2003-01-13,17.70,19.03,18.500,19.51,0.102260,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,100493,2003-02-03,9.95,10.32,9.280,10.10,-0.100775,3,0,7,...,4,0,0,0,0,0,0,0,0,0
5,1005229,2003-02-12,2.46,2.69,2.255,2.47,-0.161710,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1005731,2003-03-14,13.72,14.65,14.060,14.95,0.089650,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,100726,2003-02-10,4.55,5.20,4.780,5.35,0.175824,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1013237,2003-01-14,28.70,30.40,27.750,29.75,-0.087171,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,101594,2003-01-14,3.63,3.78,3.550,3.80,-0.066138,0,0,0,...,0,0,0,0,0,0,0,0,0,0